version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/service"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "coverage*"
      prod-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "ci"
      - "dependencies"
