-- Migration 0000_migrateit.sql
-- Created on 2025-06-10T10:03:56.354584

CREATE TABLE IF NOT EXISTS MIGRATEIT_CHANGELOG (
    id SERIAL PRIMARY KEY,
    migration_name VARCHAR(255) UNIQUE NOT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_hash VARCHAR(64) NOT NULL,
    squashed BOOLEAN DEFAULT FALSE
);

-- Rollback migration

DROP TABLE IF EXISTS MIGRATEIT_CHANGELOG;
