name: richjet code quality
on: [push]
jobs:
    test-python:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./service
        strategy:
            matrix:
                python-version: ["3.13", "3.14"]
        steps:
            - uses: actions/checkout@v5

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Pre-commit checks
              uses: pre-commit/action@v3.0.1

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest pytest-asyncio
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Pytest
              run: |
                  PYTHONPATH=. pytest
    test-vue:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        strategy:
            matrix:
                node-version: [22]
                pnpm-version: [10]
        steps:
            - uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Set node version to 22
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./web/pnpm-lock.yaml

            - run: pnpm install

            - name: Run lint
              run: pnpm run lint

            - name: Run typing
              run: pnpm run type-check

            - name: Run unit tests
              run: pnpm run test:unit

            - name: Run coverage
              run: pnpm run coverage
